 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/mobile_payments", type: :request do
  # MobilePayment. As you add validations to MobilePayment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      amount: 5.0,
      till_number: 174379,
      reason_for_payment: "ASDXCVB"
    }
  }

  let(:invalid_attributes) {
    {
      amount: nil,
      till_number: 174379,
      reason_for_payment: "ASDXCVB"
    }
  }

  describe "GET /index" do
    it "renders a successful response" do
      MobilePayment.create! valid_attributes
      get mobile_payments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      mobile_payment = MobilePayment.create! valid_attributes
      get mobile_payment_url(mobile_payment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_mobile_payment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      mobile_payment = MobilePayment.create! valid_attributes
      get edit_mobile_payment_url(mobile_payment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MobilePayment" do
        expect {
          post mobile_payments_url, params: { mobile_payment: valid_attributes }
        }.to change(MobilePayment, :count).by(1)
      end

      it "redirects to the created mobile_payment" do
        post mobile_payments_url, params: { mobile_payment: valid_attributes }
        expect(response).to redirect_to(root_url)
      end
    end

    context "with invalid parameters" do
      it "does not create a new MobilePayment" do
        expect {
          post mobile_payments_url, params: { mobile_payment: invalid_attributes }
        }.to change(MobilePayment, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post mobile_payments_url, params: { mobile_payment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mobile_payment" do
        mobile_payment = MobilePayment.create! valid_attributes
        patch mobile_payment_url(mobile_payment), params: { mobile_payment: new_attributes }
        mobile_payment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the mobile_payment" do
        mobile_payment = MobilePayment.create! valid_attributes
        patch mobile_payment_url(mobile_payment), params: { mobile_payment: new_attributes }
        mobile_payment.reload
        expect(response).to redirect_to(mobile_payment_url(mobile_payment))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        mobile_payment = MobilePayment.create! valid_attributes
        patch mobile_payment_url(mobile_payment), params: { mobile_payment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested mobile_payment" do
      mobile_payment = MobilePayment.create! valid_attributes
      expect {
        delete mobile_payment_url(mobile_payment)
      }.to change(MobilePayment, :count).by(-1)
    end

    it "redirects to the mobile_payments list" do
      mobile_payment = MobilePayment.create! valid_attributes
      delete mobile_payment_url(mobile_payment)
      expect(response).to redirect_to(mobile_payments_url)
    end
  end
end
