 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/till_numbers", type: :request do
  # TillNumber. As you add validations to TillNumber, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      doctor_name: "Murugi",
      contact_number: "0752908765",
      till_number: 12345
    }
  }

  let(:invalid_attributes) {
    {
      doctor_name: " ",
      contact_number: " ",
    
    }
  }

  describe "GET /index" do
    it "renders a successful response" do
      TillNumber.create! valid_attributes
      get till_numbers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      till_number = TillNumber.create! valid_attributes
      get till_number_url(till_number)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_till_number_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      till_number = TillNumber.create! valid_attributes
      get edit_till_number_url(till_number)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TillNumber" do
        expect {
          post till_numbers_url, params: { till_number: valid_attributes }
        }.to change(TillNumber, :count).by(1)
      end

      it "redirects to the created till_number" do
        post till_numbers_url, params: { till_number: valid_attributes }
        expect(response).to redirect_to(till_number_url(TillNumber.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TillNumber" do
        expect {
          post till_numbers_url, params: { till_number: invalid_attributes }
        }.to change(TillNumber, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post till_numbers_url, params: { till_number: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested till_number" do
        till_number = TillNumber.create! valid_attributes
        patch till_number_url(till_number), params: { till_number: new_attributes }
        till_number.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the till_number" do
        till_number = TillNumber.create! valid_attributes
        patch till_number_url(till_number), params: { till_number: new_attributes }
        till_number.reload
        expect(response).to redirect_to(till_number_url(till_number))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        till_number = TillNumber.create! valid_attributes
        patch till_number_url(till_number), params: { till_number: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested till_number" do
      till_number = TillNumber.create! valid_attributes
      expect {
        delete till_number_url(till_number)
      }.to change(TillNumber, :count).by(-1)
    end

    it "redirects to the till_numbers list" do
      till_number = TillNumber.create! valid_attributes
      delete till_number_url(till_number)
      expect(response).to redirect_to(till_numbers_url)
    end
  end
end
